[workspace]
authors = ["sanderengel <saet@itu.dk>"]
channels = ["conda-forge", "https://conda.anaconda.org/conda-forge"]
name = "gds_py"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
# Run feature engineering script
build-grid = "python feature_engineering/build_feature_grid.py"
# Run app
app = "solara run app/sol.py"

[dependencies]
python = "==3.11"
mamba = "*"
notebook = "*"
jupyterhub = "*"
jupyterlab = "*"
blas = { build = "openblas", channel = "conda-forge" }
black = "*"
bokeh = "*"
boto3 = "*"
bottleneck = "*"
cenpy = "*"
clustergram = "*"
contextily = "*"
cython = "*"
dask = "*"
dask-geopandas = "*"
datashader = "*"
flake8 = "*"
geocube = "*"
geopandas = "*"
geopy = "*"
gstools = "*"
h3-py = "*"
hdbscan = "*"
ipyleaflet = "*"
ipympl = "*"
ipywidgets = "*"
jupyter_bokeh = "*"
jupytext = "*"
legendgram = "*"
lxml = "*"
momepy = "*"
nbdime = "*"
netcdf4 = "*"
networkx = "*"
openpyxl = "*"
osmnx = "*"
palettable = "*"
pandana = "*"
pip = "*"
polyline = "*"
pooch = "*"
psycopg2 = "*"
pyarrow = "*"
pygeos = "*"
pyogrio = "*"
pyppeteer = "*"
pyrosm = "*"
pysal = "*"
pystac-client = ">=0.9.0,<0.10"
rasterio = ">=1.3.8,<2"
rasterstats = "*"
rio-cogeo = "*"
rioxarray = "*"
scikit-learn = "*"
scikit-mobility = "*"
seaborn = "*"
spatialpandas = "*"
sqlalchemy = "*"
statsmodels = "*"
tabulate = "*"
urbanaccess = "*"
xarray-spatial = ">=0.5.3,<0.6"
xarray_leaflet = "*"
xlrd = "*"
xlsxwriter = "*"
ca-certificates = "*"
certifi = "*"
openssl = "*"
geoalchemy2 = "*"
pygeoda = "*"
topojson = "*"
matplotlib-scalebar = "*"
pytest-cov = "*"
pytest-tornasync = "*"
ipykernel = ">=6.30.1,<7"
solara = ">=1.51.0,<2"
leafmap = ">=0.54.0,<0.55"
haversine = ">=2.9.0,<3"
spaghetti = ">=1.7.6,<2"
planetary-computer = ">=1.0.0,<2"
stackstac = ">=0.5.1,<0.6"
xarray = ">=2025.6.1,<2026"
